version: '3'

services:
  app:
    build: .
    container_name: python-redis
    restart: always
    ports:
      - "8080:8000"
    depends_on:
      - redis
    volumes:
      - app:/app

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    ports:
      - "6379"

volumes:
  app:
